# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


class Ui_ImageFilter(object):
    def setupUi(self, ImageFilter):
        ImageFilter.setObjectName("ImageFilter")
        ImageFilter.resize(1212, 895)
        ImageFilter.setStyleSheet("background-color: rgb(19, 19, 43);\n"
"")
        self.centralwidget = QtWidgets.QWidget(ImageFilter)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setIndent(2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Original_image = QtWidgets.QLabel(self.centralwidget)
        self.Original_image.setScaledContents(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Original_image.sizePolicy().hasHeightForWidth())
        self.Original_image.setSizePolicy(sizePolicy)
        self.Original_image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Original_image.setText("")
        self.Original_image.setObjectName("Original_image")
        self.verticalLayout.addWidget(self.Original_image)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 95)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.figure_of_original_histo = Figure()
        self.axes_of_original_histo = self.figure_of_original_histo.add_subplot(1, 1, 1)
        self.canvas_of_original_histo = FigureCanvas(self.figure_of_original_histo)
        self.verticalLayout_2.addWidget(self.canvas_of_original_histo)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 95)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.figure_of_original_freq = Figure()
        self.axes_of_original_freq = self.figure_of_original_freq.add_subplot(1, 1, 1)
        self.canvas_of_original_freq = FigureCanvas(self.figure_of_original_freq)
        self.verticalLayout_3.addWidget(self.canvas_of_original_freq)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 95)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 20)
        self.horizontalLayout.setStretch(1, 20)
        self.horizontalLayout.setStretch(2, 20)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.Filtered_Image = QtWidgets.QLabel(self.centralwidget)
        self.Filtered_Image.setScaledContents(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Filtered_Image.sizePolicy().hasHeightForWidth())
        self.Filtered_Image.setSizePolicy(sizePolicy)
        self.Filtered_Image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Filtered_Image.setText("")
        self.Filtered_Image.setObjectName("Filtered_Image")
        self.verticalLayout_4.addWidget(self.Filtered_Image)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 95)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.figure_of_filtered_histo = Figure()
        self.axes_of_filtered_histo = self.figure_of_filtered_histo.add_subplot(1, 1, 1)
        self.canvas_of_filtered_histo = FigureCanvas(self.figure_of_filtered_histo)
        self.verticalLayout_5.addWidget(self.canvas_of_filtered_histo)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 95)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.figure_of_filtered_freq = Figure()
        self.axes_of_filtered_freq = self.figure_of_filtered_freq.add_subplot(1, 1, 1)
        self.canvas_of_filtered_freq = FigureCanvas(self.figure_of_filtered_freq)
        self.verticalLayout_6.addWidget(self.canvas_of_filtered_freq)
        self.verticalLayout_6.setStretch(0, 5)
        self.verticalLayout_6.setStretch(1, 95)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.setStretch(0, 20)
        self.horizontalLayout_2.setStretch(1, 20)
        self.horizontalLayout_2.setStretch(2, 20)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.Upload_The_Image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Upload_The_Image.sizePolicy().hasHeightForWidth())
        self.Upload_The_Image.setSizePolicy(sizePolicy)
        self.Upload_The_Image.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 0);\n"
"font: 75 14pt \"Franklin Gothic Medium\";\n"
"border:none;\n"
"padding-top:5px;\n"
"border-radius:8px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(8, 186, 20);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 155, 0);\n"
"}")
        self.Upload_The_Image.setIconSize(QtCore.QSize(20, 20))
        self.Upload_The_Image.setObjectName("Upload_The_Image")
        self.verticalLayout_7.addWidget(self.Upload_The_Image)
        self.Choose_Filter = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Choose_Filter.sizePolicy().hasHeightForWidth())
        self.Choose_Filter.setSizePolicy(sizePolicy)
        self.Choose_Filter.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 75 14pt \"Franklin Gothic Medium\";\n"
"border:none;\n"
"padding-top:5px;\n"
"border-radius:8px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Choose_Filter.setObjectName("Choose_Filter")
        self.Choose_Filter.addItem("")
        self.Choose_Filter.addItem("")
        self.Choose_Filter.addItem("")
        self.Choose_Filter.addItem("")
        self.Choose_Filter.addItem("")
        self.Choose_Filter.addItem("")
        self.verticalLayout_7.addWidget(self.Choose_Filter)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)

        self.Apply_Equalization = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Apply_Equalization.sizePolicy().hasHeightForWidth())
        self.Apply_Equalization.setSizePolicy(sizePolicy)
        self.Apply_Equalization.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 0);\n"
"font: 75 14pt \"Franklin Gothic Medium\";\n"
"border:none;\n"
"padding-top:5px;\n"
"border-radius:8px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(8, 186, 20);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 155, 0);\n"
"}")
        self.Apply_Equalization.setObjectName("Apply_Equalization")
        self.gridLayout.addWidget(self.Apply_Equalization, 1, 0, 1, 1)
        ImageFilter.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ImageFilter)
        self.statusbar.setObjectName("statusbar")
        ImageFilter.setStatusBar(self.statusbar)
        self.Upload_An_Image = QtWidgets.QAction(ImageFilter)
        self.Upload_An_Image.setCheckable(False)
        self.Upload_An_Image.setObjectName("Upload_An_Image")

        self.retranslateUi(ImageFilter)
        QtCore.QMetaObject.connectSlotsByName(ImageFilter)

    def retranslateUi(self, ImageFilter):
        _translate = QtCore.QCoreApplication.translate
        ImageFilter.setWindowTitle(_translate("ImageFilter", "ImageFilter"))
        self.label.setText(_translate("ImageFilter", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Original Image</span></p></body></html>"))
        self.label_3.setText(_translate("ImageFilter", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Histogram</span></p></body></html>"))
        self.label_4.setText(_translate("ImageFilter", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Frequency Domain</span></p></body></html>"))
        self.label_2.setText(_translate("ImageFilter", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Filtered Image</span></p></body></html>"))
        self.label_5.setText(_translate("ImageFilter", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Histogram</span></p></body></html>"))
        self.label_6.setText(_translate("ImageFilter", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Frequency Domain</span></p></body></html>"))
        self.Upload_The_Image.setText(_translate("ImageFilter", "Upload An Image"))
        self.Choose_Filter.setItemText(0, _translate("ImageFilter", "Sharpening Filter"))
        self.Choose_Filter.setItemText(1, _translate("ImageFilter", "Bilateral Filter"))
        self.Choose_Filter.setItemText(2, _translate("ImageFilter", "MedianBlur Filter"))
        self.Choose_Filter.setItemText(3, _translate("ImageFilter", "Laplacian Filter"))
        self.Choose_Filter.setItemText(4, _translate("ImageFilter", "Frequency HighPass Filter"))
        self.Choose_Filter.setItemText(5, _translate("ImageFilter", "Frequency LowPass Filter"))
        self.Apply_Equalization.setText(_translate("ImageFilter", "Apply Equalization"))
        self.Upload_An_Image.setText(_translate("ImageFilter", "Upload An Image"))
